title = "Fintern"
baseURL = "https://xenodochial-jepsen-d22178.netlify.app/"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes"
resourceDir = "resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Your one stop shop for commercial awarness"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "m-b-m-ZzOa5G8hSPI-unsplash.jpg"
  recent_posts_number = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true